apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-complik
  name: service-complik-config
  namespace: sealos
data:
  config.yml: |
    plugins:
      - name: "Complete"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "intervalMinute": 10080,
            "autoStart": false,
            "startTimeSecond": 30
          }

      - name: "Devbox"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "intervalMinute": 3000,
            "autoStart": true,
            "startTimeSecond": 30
          }

      - name: "Endpointslice"
        type: "Discovery"
        enabled: false
        settings: '{}'

      - name: "Deployment"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "resyncTimeSecond": 5,
            "ageThresholdSecond": 300
          }

      - name: "StatefulSet"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "resyncTimeSecond": 5,
            "ageThresholdSecond": 300
          }

      - name: "Browser"
        type: "Compliance"
        enabled: true
        settings: |
          {
            "timeout": 100,
            "maxWorkers": 20
          }

      - name: "Safety"
        type: "Compliance"
        enabled: true
        settings: |
          {
            "apiKey": "sk-1sxAT9tTxxUCiBobRJSOaYC4BFPKLdyhypXg7o9eJsmaDFhU",
            "apiBase": "https://aiproxy.usw.sealos.io/v1",
            "apiPath": "/chat/completions",
            "model": "gpt-5"
          }

      - name: "Custom"
        type: "Compliance"
        enabled: false
        settings: |
          {
            "databaseName": "custom",
            "tickerMinute": 800,
            "maxWorkers": 20,
            "host": "dbconn.sealoshzh.site",
            "port": "33144",
            "username": "root",
            "password": "l6754g75",
            "tableName": "CustomKeywordRule",
            "apiKey": "sk-1sxAT9tTxxUCiBobRJSOaYC4BFPKLdyhypXg7o9eJsmaDFhU",
            "apiBase": "https://aiproxy.usw.sealos.io/v1",
            "apiPath": "/chat/completions",
            "model": "gpt-5"
          }

      - name: "Postgres"
        type: "Handle"
        enabled: true
        settings: |
          {
            "region": "hzh",
            "host": "dbconn.sealoshzh.site",
            "port": "33144",
            "username": "root",
            "password": "l6754g75"
          }

      - name: "Lark"
        type: "Handle"
        enabled: true
        settings: |
          {
            "region": "hzh",
            "webhook": "https://open.feishu.cn/open-apis/bot/v2/hook/57e00497-a1da-41cd-9342-2e645f95e6ec"
          }
    logging:
      level: "info"
    kubeconfig: "/kubeconfig/kubeconfig.yml"
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-complik
  name: service-complik-kubeconfig
  namespace: sealos
data:
  kubeconfig.yml: |
    apiVersion: v1
    kind: Config
    users:
      - name: read-only
        user:
          token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlGc0g3a2JCNFo2R1BpczRDRlA1Ykhkb2VNSlVIMU1PZ1ktYUpyVDJrd28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJyZWFkLW9ubHktbnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmVhZC1vbmx5Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InJlYWQtb25seSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2NmNiNmVjLTk2NjctNDJhZi04NzJmLTU4MWUyYTFmZmUzZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpyZWFkLW9ubHktbnM6cmVhZC1vbmx5In0.NnWKAydcyISiaz7LQZ19f_GNYlpBkbW9_4xxd7HdYSbvLnG11gurTBzsr_clKhFNTNQlbKdJFCU14cAJNDdCTmqPpmG5nbD0mEpZjgGDAfXvQp8ZStwsXZURxLQ_pDgcujY01iUMWVQltBMsTLgIG9RdJa1VC6sySs9sw_Xesd6rL7_zbbSmirKZ6R_Ozq3kOND21HKRJ9_vcGO7HaFbi_QE090RMc3ZQrMq1zwMYpQYLb6BlafjbYHCt0hFff91L_VCIrl_-YPMhYC2otKlGlzypRXYJPX2V5B4Wv7H-gZKT7WzUDSNt6JidKsjKYpeeD6qwfxxZR9eUQ295a_Hsg
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJME1ERXlOVEUxTkRjek1Gb1lEekl4TWpRd01UQXhNVFUwTnpNd1dqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjFVUXlZdUp0Z3JlUmhBOStFaGNSQURGZmFzRCtVZUljM0ZSVG1Ha05QYXZpclkwV2tNU2Z2TzVXb2o2aFROS0YKYk5mTWd2OWdQejcyelRKUVhHaVNkWmVaSlN6dnROQUZTNng1QWFxRGJweTY3UlNjM001Umpvc3I0MU5vZFRaQgpVRVk4WHB6dlE4cVhqMll4VjZ4Y1N5dmFjUUsrMEUwTVljQVZmVWxQVk9LTTNaZGdSSjYrRU0vblJpeFBySzlGCnRaaHhyamlrUmQrV2JZUHJOcExseTBIUFZRbXZONWdyOE9DaW1YNVk4SWdKQy84cjkrR0FaMWdxMCt0V1FpLzkKWmc2WUF6bUxJMi9JRy8xeW5tTlJoUXE5MVh4MTFzekc0bDJqUThUMXhrSWN6cTY3cytSOTl3RSt6c0VlNlJXQwpGSTY0SHFrejU3M1BZNlVyZGRiQmJRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVYL2JwY0l1RlBCelZsWG1UV0NJZ1c5NU5VbW93RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFESGxXN1BNbldXNEk1bzJMOUEzdXREVWo1YThjTzhiK0phNmJqeTUwQzlFQk1hUQpRTjJHQUdJK1RHdjNSVWtwRUxtTm1sRTk1RzBwNXdMaE5aRDBqanovVlpwQWtMK2FsYjljc09yQlZlQXg2cVNXCldjc2svNGNkVHdHa2ZaM01QbDRjR0FscDFKQklwaEYxeGMvSCtZYkU4U25RcDNrckgyTzVmY2pqT1hGaWxCYUUKZHlBSVRlVi90ckZhQnVvaUFzbDdjM25hNG9rbENnS3hrcjZJbmVlcTlTUGhjb0FWY09pdXM5bGJzSVBSNUZFUgoyS0llYmllV3NJVUlYVE5WRDJhWUV3WVVTRVRYZU9MUXFETmlEMGg4UkltYWdhN2JmMVorYzkzUlNRV0MrOXFhCm5yc2haT1FJZ1ZOa0NCbDRCV2xQcDA5OXhvQ1h6TEtqU3RYYlNLcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          server: https://hzh.sealos.run:6443
        name: kubernetes
    contexts:
      - context:
          cluster: kubernetes
          user: read-only
        name: read-only-context
    current-context: read-only-context
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-complik
  name: service-complik-deployment
  namespace: sealos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-complik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-complik
    spec:
      containers:
        - args:
            - --config=/config/config.yml
          command:
            - /manager
          image: bearslyricattack/sealos-complik-service:latest
          imagePullPolicy: Always
          name: service-complik
          ports:
            - containerPort: 8428
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config-vol
            - mountPath: /kubeconfig
              name: kubeconfig-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: service-complik-config
          name: config-vol
        - configMap:
            defaultMode: 420
            name: service-complik-kubeconfig
          name: kubeconfig-vol
