node_name: "security-monitor-node"
proc_path: "proc"
scan_interval: 10

processes:
  - "nc"
  - "netcat"
  - "ncat"
  - "socat"
  - "telnet"
  - "ssh"
  - "scp"
  - "rsync"
  - "wget"
  - "curl"
  - "python"
  - "perl"
  - "ruby"
  - "bash"
  - "sh"
  - "zsh"

keywords:
  - "reverse_shell"
  - "backdoor"
  - "malware"
  - "exploit"
  - "payload"
  - "/tmp/"
  - "/dev/shm/"
  - "base64"
  - "encode"
  - "decode"
