plugins:
  - name: "Complete"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "intervalMinute": 10080,
        "autoStart": true,
        "startTimeSecond": 30
      }

  - name: "Devbox"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "intervalMinute": 3000,
        "autoStart": false,
        "startTimeSecond": 30
      }

  - name: "Endpointslice"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "Deployment"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "resyncTimeSecond": 5,
        "ageThresholdSecond": 300
      }

  - name: "StatefulSet"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "resyncTimeSecond": 5,
        "ageThresholdSecond": 300
      }

  - name: "Browser"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "timeout": 100,
        "maxWorkers": 20
      }

  - name: "Safety"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "apiKey": "${SAFETY_API_KEY}",
        "apiBase": "${SAFETY_API_BASE}",
        "apiPath": "/chat/completions",
        "model": "gpt-5"
      }

  - name: "Custom"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "databaseName": "custom",
        "tickerMinute": 800,
        "maxWorkers": 20,
        "host": "${DB_HOST}",
        "port": "${DB_PORT}",
        "username": "${DB_USERNAME}",
        "password": "${DB_PASSWORD}",
        "tableName": "CustomKeywordRule",
        "apiKey": "${CUSTOM_API_KEY}",
        "apiBase": "${CUSTOM_API_BASE}",
        "apiPath": "/chat/completions",
        "model": "gpt-5"
      }

  - name: "Postgres"
    type: "Handle"
    enabled: true
    settings: |
      {
        "region": "${REGION}",
        "host": "${POSTGRES_HOST}",
        "port": "${POSTGRES_PORT}",
        "username": "${POSTGRES_USERNAME}",
        "password": "${POSTGRES_PASSWORD}"
      }

  - name: "Lark"
    type: "Handle"
    enabled: true
    settings: |
      {
        "region": "${REGION}",
        "webhook": "${LARK_WEBHOOK}",
        "enabled_whitelist": true,
        "host": "${LARK_DB_HOST}",
        "port": "${LARK_DB_PORT}",
        "username": "${LARK_DB_USERNAME}",
        "password": "${LARK_DB_PASSWORD}",
        "host_timeout_hour": 168
      }

logging:
  level: "info"

kubeconfig: "${KUBECONFIG_PATH}"