plugins:
  - name: "Cron"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "test": "测试11111111"
      }

  - name: "EndPointInformer"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "DeploymentInformer"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "Collector"
    type: "Compliance"
    enabled: true
    settings: '{}'

  - name: "Website"
    type: "Compliance"
    enabled: true
    settings: '{}'

  - name: "Database"
    type: "Handle"
    enabled: true
    settings: '{}'

  - name: "Lark"
    type: "Handle"
    enabled: true
    settings: '{}'

logging:
  level: "info"

kubeconfig: "gzg.yml"