plugins:
  - name: "Complete"
    type: "Discovery"
    enabled: true
    settings: '{}'

  - name: "Devbox"
    type: "Discovery"
    enabled: true
    settings: '{}'

  - name: "Endpointslice"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "Deployment"
    type: "Discovery"
    enabled: true
    settings: '{}'

  - name: "StatefulSet"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "Browser"
    type: "Compliance"
    enabled: true
    settings: '{}'

  - name: "Safety"
    type: "Compliance"
    enabled: true
    settings: '{}'

  - name: "Postgres"
    type: "Handle"
    enabled: true
    settings: '{}'

  - name: "Lark"
    type: "Handle"
    enabled: true
    settings: '{}'

logging:
  level: "info"

kubeconfig: "gzg.yml"