apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: {{ .Values.database.name }}
    app.kubernetes.io/instance: {{ .Values.database.name }}
    app.kubernetes.io/managed-by: kbcli
  name: {{ .Values.database.name }}
  namespace: {{ .Values.database.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: {{ .Values.database.name }}
    app.kubernetes.io/instance: {{ .Values.database.name }}
    app.kubernetes.io/managed-by: kbcli
  name: {{ .Values.database.name }}
  namespace: {{ .Values.database.namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: {{ .Values.database.name }}
    app.kubernetes.io/instance: {{ .Values.database.name }}
    app.kubernetes.io/managed-by: kbcli
  name: {{ .Values.database.name }}
  namespace: {{ .Values.database.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.database.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.database.name }}
    namespace: {{ .Values.database.namespace }}
