{{- if .Values.database.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: complik-db
    app.kubernetes.io/instance: complik-db
    app.kubernetes.io/managed-by: kbcli
    app: {{ .Values.app.name }}
  name: complik-db
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: complik-db
    app.kubernetes.io/instance: complik-db
    app.kubernetes.io/managed-by: kbcli
    app: {{ .Values.app.name }}
  name: complik-db
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: complik-db
    app.kubernetes.io/instance: complik-db
    app.kubernetes.io/managed-by: kbcli
    app: {{ .Values.app.name }}
  name: complik-db
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: complik-db
subjects:
  - kind: ServiceAccount
    name: complik-db
    namespace: {{ .Values.namespace }}
{{- end }}
