apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: process-scanner
  namespace: security
spec:
  selector:
    matchLabels:
      app: process-scanner
  template:
    metadata:
      labels:
        app: process-scanner
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: scanner
          image: process-scanner:latest
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMPLIANCE_URL
              value: "http://compliance-service:8080/alert"
            - name: SCAN_INTERVAL
              value: "30"
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /config
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: scanner-config
