---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: process-scanner
  namespace: sealos
automountServiceAccountToken: true

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: process-scanner
rules:
  # 读取 Pod 信息
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # 读取节点信息
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # 创建事件
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # 读取命名空间信息
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: process-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: process-scanner
subjects:
  - kind: ServiceAccount
    name: process-scanner
    namespace: sealos

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: proc-scan-config
  namespace: sealos
data:
  config.yaml: |
    node_name: "security-monitor-node"
    proc_path: "/host/proc"
    scan_interval: 100
    processes:
      - "miner"
      - "agsb"
      - "cloudflar"
      - "ssh"
    keywords:
---
# DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proc-scan
  namespace: sealos
  labels:
    app: proc-scan
    version: v1.0.0
spec:
  selector:
    matchLabels:
      app: process-scanner
  template:
    metadata:
      labels:
        app: process-scanner
        version: v1.0.0
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: process-scanner
      containers:
        - name: scanner
          image: bearslyricattack/sealos-complik-procscan:latest
          imagePullPolicy: Always
          command: [ "/manager" ]
          args:
            - "--config=/config/config.yaml"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
            - name: containerd-sock
              mountPath: /var/run/containerd/containerd.sock
              readOnly: false
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: config
          configMap:
            name: proc-scan-config
            defaultMode: 0644
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
