---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: process-scanner
  namespace: sealos
automountServiceAccountToken: true

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: process-scanner
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "update", "patch"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: process-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: process-scanner
subjects:
  - kind: ServiceAccount
    name: process-scanner
    namespace: sealos

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: proc-scan-config
  namespace: sealos
data:
  config.yaml: |
    # 扫描器自身配置
    scanner:
      proc_path: "/host/proc"
      scan_interval: "100s"
      log_level: "info"

    # 自动化动作配置
    actions:
      annotation:
        enabled: true
        data:
          debt.sealos/status: "Suspend"
      forceDelete:
        enabled: false # 默认关闭，保证安全

    # 通知渠道配置
    notifications:
      lark:
        webhook: ""

    # 检测规则配置
    detectionRules:
      blacklist:
        processes:
          - "^miner$" # 精确匹配 miner
          - "agsb"
        keywords:
          - "xmr.pool.gulf.obtc.com"
      whitelist:
        processes:
          - "legit-process"
        commands:
          - "/usr/bin/bash -c 'legit-script'"
        namespaces:
          - "ns-dev-test"
        podNames:
          - "special-debug-pod-"
---
# DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proc-scan
  namespace: sealos
  labels:
    app: proc-scan
    version: v1.0.0
spec:
  selector:
    matchLabels:
      app: process-scanner
  template:
    metadata:
      labels:
        app: process-scanner
        version: v1.0.0
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: process-scanner
      containers:
        - name: scanner
          image: layzer/sealos-procscan:v0.0.2-alpha-6
          imagePullPolicy: Always
          command: [ "/manager" ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "--config=/config/config.yaml"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
            - name: containerd-sock
              mountPath: /var/run/containerd/containerd.sock
              readOnly: false
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 50m
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: config
          configMap:
            name: proc-scan-config
            defaultMode: 0644
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
